### ISSUE TITLE
Gruntfile.js - grunt-asset-injector

### ISSUE THREAD

**Issue by clanshood** [clanshood/smart-paper#1]
ada masalah pada options.ignorePath, kaya'e kok ga fungsi.
nek bisa tolong dibantu kk @moszes

**Comment by clanshood** [comment]
[referensi](https://github.com/DaftMonk/grunt-asset-injector)

**Comment by mahatmamahardhikach** [comment]
sek ya kk sori ki durung isa coding, kondisi sedang tidak memungkinkan ..., secepatnya menyesuaikan
